on:
  push:
    tags:
      - 'v*'
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/checkout@v2
      - env:
          GITHUB_KEY: ${{ secrets.GH_KEY }}
          GITHUB_SECRET: ${{ secrets.GH_SECRET }}
          GITLAB_KEY: ${{ secrets.GITLAB_KEY }}
          GITLAB_SECRET: ${{ secrets.GITLAB_SECRET }}
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
        run: ./scripts/prepare-providers.sh
      - run: make release
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: release/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}